# -*- coding: utf-8 -*-
"""PandasMatplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XfikNHcAnCcD7PU1odi79CjG6mrMInHf
"""

import numpy as np
l=[[1,2,3,4,5,6]]
a1=np.array(l)
print('Array before transpose')
print(a1)
print(a1.shape)
print('Array after transpose')
a1=a1.T
print(a1)
a1.shape

a1=np.array([[1,2,3]])
a2=np.array([[1,2],[4,5],[7,8]])
print('Shape of Array a1:', a1.shape)
print('Shape of Array a2:', a2.shape)
a3=np.matmul(a1,a2)
print(a3)
print('Shape of Array a3:',a3.shape)

import pandas as pd
type_house= pd.Series(['Loft','Villa'])
type_house

df=pd.DataFrame({'Price':[100000,300000],'data_construction':[1960,2010]})
df.head()

from matplotlib import pyplot as plt

plt.plot([32,26,43,41,16,37,29])
plt.ylabel('marks out of 50')
plt.xlabel('Roll number')
plt.show()

plt.plot([32,26,43,41,16,37,29],[1,2,3,4,5,6,7],'y*')
plt.ylabel('marks out of 50')
plt.xlabel('Roll number')
plt.show()

#creating fig
fig=plt.figure(figsize=[7,5], facecolor='pink', edgecolor='b')
#adding axex to fig
ax=fig.add_axes([0,0,1,1])
ax.set_title("New figure and axes")
ax.set_xlabel('X-Axis')
ax.set_ylabel('Y_Axis')

#creating fig
fig=plt.figure(figsize=[7,5], facecolor='skyblue', edgecolor='b')
#adding axex to fig
ax=fig.add_axes([0,0,1,1])
ax.set_title("Example line plot")
ax.set_xlabel('roll no.')
ax.set_ylabel('marks out of 50')
plt.plot([1,2,3,4,5,6,7],[90,99,96,95,92,94,90])
plt.show()

#subplot
fig, (ax1, ax2)= plt.subplots(1,2, figsize=[12,5], facecolor='skyblue', edgecolor='b')
fig.suptitle('Example Subplots')
ax1.plot([1,2,3,4,5,6,7],[32,45,12,67,89,45,98])
ax1.set_title("Class1")
ax1.set_xlabel('roll no.')
ax1.set_ylabel('marks out of 50')

ax2.plot([1,2,3,4,5,6,7],[84,29,45,90,98,97,95],color='g')
ax2.set_title("Class 2")
ax2.set_xlabel('roll no.')
ax2.set_ylabel('marks out of 50')
plt.show()

#subplot
fig, (ax1, ax2, ax3)= plt.subplots(1,3, figsize=[12,5], facecolor='skyblue', edgecolor='b')
fig.suptitle('Example Subplots')
ax1.plot([1,2,3,4,5,6,7],[32,45,12,67,89,45,98])
ax1.set_title("Class1")
ax1.set_xlabel('roll no.')
ax1.set_ylabel('marks out of 50')

ax2.plot([1,2,3,4,5,6,7],[84,29,45,90,98,97,95],color='g')
ax2.set_title("Class 2")
ax2.set_xlabel('roll no.')
ax2.set_ylabel('marks out of 50')

ax3.plot([1,2,3,4,5,6,7],[88,87,89,80,90,91,92])
ax3.set_title("Class3")
ax3.set_xlabel('roll no.')
ax3.set_ylabel('marks out of 50')
plt.show()



""" a line plot visualizes information as a series of data points called **markers** connected by straight line segments."""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
#creating a matplotlib line plot
#load the dataset
data={'Days': ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
      'Week 1': [27,29,30,31,33,34,28],
      'Week 2': [29,30,31,32,30,29,28],
      'Week 3': [25,26,27,28,23,30,29]}
df=pd.DataFrame(data)
df

plt.plot(df['Days'],df['Week 1'])

week1=plt.plot(df['Days'],df['Week 1'])
week2=plt.plot(df['Days'],df['Week 2'])
week3=plt.plot(df['Days'],df['Week 3'])
plt.xlabel('Days')
plt.ylabel('Temprature')
plt.title('Line plot for 3 weeks temperatures')
plt.legend(['Week1', 'Week2','Week3'])
plt.show()

week1=plt.plot(df['Days'],df['Week 1'])
week2=plt.plot(df['Days'],df['Week 2'])
week3=plt.plot(df['Days'],df['Week 3'])
plt.xlabel('Days')
plt.ylabel('Temprature')
plt.title('Line plot for 3 weeks temperatures')
plt.legend(['Week1', 'Week2','Week3'])
plt.show()

week1=plt.plot(df['Days'],df['Week 1'],c='skyblue', ls='-.')
week2=plt.plot(df['Days'],df['Week 2'],c='lightgreen',ls='dashed')
week3=plt.plot(df['Days'],df['Week 3'],c='magenta', ls=':')
plt.xlabel('Days')
plt.ylabel('Temprature')
plt.title('Line plot for 3 weeks temperatures')
plt.legend(['Week1', 'Week2','Week3'])
plt.show()

week1=plt.plot(df['Days'],df['Week 1'],c='skyblue', ls='-.')
week2=plt.plot(df['Days'],df['Week 2'],c='lightgreen',ls='dashed')
week3=plt.plot(df['Days'],df['Week 3'],c='magenta', ls=':', lw=3)
plt.xlabel('Days')
plt.ylabel('Temprature')
plt.title('Line plot for 3 weeks temperatures')
plt.legend(['Week1', 'Week2','Week3'])
plt.show()

import matplotlib.pyplot as plt
x=[5,78,7,2,17,2,9,4,11,12,9,6]
y=[99,86,87,88,111,86,103,87,94,78,77,85]
plt.scatter(x,y)
plt.show()