# -*- coding: utf-8 -*-
"""pythonBasics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KKXCu9QmPwcHHWBjoTZWfVgkPk39hWso
"""

print("5>2")

""" Tanishka is female CR """
#this is single line comment
print(5)

a= int(input("Enter integer: "))
b= float(input("Enter floating number: "))
c=str(input("Enter string: "))
x=5
y=5.5
z="India"
print(a,b,c,x,y,z)

# python datatypes: Numeric and Sequence
# int, float, comlex for Numeric
# list, tuple, string for Sequence

l=[1,2,3,3.5]
t=(1,2,3)
str1="Hello"
print(l,t,str1)

#Python casting
x=12
y=float(x)
a=2.8
b=int(a)
print(x,y,a,b)

y=float("3")
print(y)

x=2
y=str(x)
print(y)

#tuple can not be changed

a="Hello K23SK"
#uppercase and 3rd element slice string index 2 to 4
print(a[2])
print(a[2:5])
print(a.upper())

#Python operators
print(5+3)
print(3-1)
print(4*2)
print(80/2)
print(23%2)

#Python List
l=[1,2,3.4,"Hello",(5,6,7)]
print(l)
print(l[4][1])
print(l[3])
l[0]=0
print(l[0])
l.append("World")
print(l)

#Python Sets: unordered collection of unique elements
s={12,43,12,45,67}
print(s)
s.add(10)
print(s)

#Python dictionary: {key: value} pair
dictionary1={"Monday": 19, "Tuesday": 20}
print(dictionary1)

#if-else statements
x=6
if x>5:
  print("X>5")
else:
  print("X<5")

#while loop
x=10
while x>0:
  print(x)
  x=x-1

#for loop
fruit=["banana","mango","cherry"]
for i in fruit:
  print(i)

#function
def greet(name):
  print("Hello",name)
greet('Raj')

#Python arrays
array1=["BMW", "Audi", "Maruti", "Hundai"]
print(array1[2])

